### ISSUE TITLE
Proposal: IO Signature

### ISSUE THREAD

**Issue by djspiewak** [alexandru/schrodinger#2]
```scala
sealed class IO[+A] {

  def map[B](f: A => B): IO[B] = ???
  def flatMap[B](f: A => IO[B]): IO[B] = ???

  def attempt: IO[Either[Throwable, A]] = ???

  def unsafeRunSync(): A = ???
  def unsafeRunAsync(cb: A => Unit): Unit = ???
  def unsafeRunTimed(limit: FiniteDuration): A = ???
}

object IO {

  def eval[A](ea: Eval[A]): IO[A] = ???
  def apply[A](a: => A): IO[A] = eval(Eval.always(a))
  def async[A](cb: (Either[Throwable, A] => Unit) => Unit): IO[A] = ???
  def fail(t: Throwable): IO[Nothing] = ???
}
```

Some things to discuss:

- Covariance?
- ~~Do we need `now`?  Someone with a better handle on the performance impact of the new lambda encoding for by-name parameters should weigh in here~~
  + ~~Can we just use `apply` instead of `delay`?  (to be clear, this would just be a rename of the above, not a new function that takes an `ExecutionContext`)~~
  + ~~Another idea here would be to have a constructor which takes `Eval[A]` and a convenience constructor which just takes `=> A`~~
    * I just changed it to this
- We need to be sure we expose the algebra for introspection, to enable the implementation of sane downstream stuff (e.g. `fork`)

**Comment by alexandru** [comment]
@djspiewak I have had this policy of not blocking threads, which can be quite sane. 

`unsafeRunSync` can't be supported over Javascript and it's unsafe not just because it can trigger side-effects, but also in the Java-sense as well.  So to preserve familiarity, I propose the following:

1. It should have a `timeout` parameter (just like `Await.result`), after which it should throw a `TimeoutException`
2. On top of Javascript, we need to try and evaluate the result synchronously and if we hit an async boundary, then we have no choice but to trigger an exception

We should also have the following variant, which also tries to run synchronously, falling back to the provided callback.

```scala
def unsafeRunSyncAttempt(cb: Attempt[A] => Unit): Either[Unit, A]
```

I also don't agree with the normal run because we *need* a way to signal exceptions, otherwise there won't be any way to catch them (for example I don't think we can implement `ApplicativeError` either):

```scala
type Attempt[A] = Either[Throwable, A]

def unsafeRunAsync(cb: Attempt[A] => Unit): Unit
```

On to your points:

- Covariance - I would prefer it, had no problem in Monix's Task with it - being a data-type that doesn't do HKT, I don't think we can hit any issues; but then I don't have strong feelings on it
- We should do `now` because such instances are very common and thunks do have a performance impact - it will be just an extra state, which we can reuse for errors as well, so it could be `Now(value: Attempt[A])

BTW, I don't see Schrodinger as the project where we'll implement `IO`. This is OK, right?

I mean, we need a `cats-effects` and `schrodinger-core` is meant to be minimal and extremely stable (no `cats-core` dependency), because I actually have a hope that one day Scalaz will integrate with it and maybe others as well :-)

I'm trying to move this project to the Typelevel.org.
Can I add you to the Maintainers list? :-)

**Comment by djspiewak** [comment]
> It should have a timeout parameter (just like Await.result), after which it should throw a TimeoutException

That's what `unsafeRunTimed` is for.  In my experience, this function really isn't relevant outside of testing.  If you're using it in some sort of mainline production code, there's a problem *somewhere*.

> On top of Javascript, we need to try and evaluate the result synchronously and if we hit an async boundary, then we have no choice but to trigger an exception

I forgot about JavaScript.  I have some mostly-congeled thoughts on that.  More later…

> `def unsafeRunAsync(cb: Attempt[A] => Unit): Unit`

That's just sugar for `ioa.attempt.unsafeRunAsync`.  I don't like how `unsafeRun` returns `A` while `unsafeRunAsync` (in your formulation) wraps in `Attempt`.  But then again, my formulation makes `unsafeRunAsync` asymmetric with `async`.  I'm ok with either one.

> BTW, I don't see Schrodinger as the project where we'll implement IO. This is OK, right?

Why not?

> because I actually have a hope that one day Scalaz will integrate with it and maybe others as well :-)

That seems very unlikely, especially since Scalaz is trying to get out of the "having a `Task`" business (or at least, elements within Scalaz).  As I said on the other issue, without a "real" reference implementation, this project doesn't really answer anyone's use-case.

> I'm trying to move this project to the Typelevel.org.
> Can I add you to the Maintainers list? :-)

Let's figure out some of the concrete stuff first.  :-D

**Comment by alexandru** [comment]
>  As I said on the other issue, without a "real" reference implementation, this project doesn't really answer anyone's use-case.

Well, an `IO` implementation is more difficult than providing a couple of interfaces meant for middleware and is going to be more unstable.

I was thinking of `schrodinger-core` to be like the [reactive-streams](http://www.reactive-streams.org/) specification in spirit.  So `schrodinger-core` is middleware and other non-Cats projects won't want to depend on it's not very light and very stable.

We can make `cats-effects` depend on `schrodinger-core`.

I would be fine to have `schrodinger-effects` (or something) as a sub-project if that's what you propose - but IMO `cats-effects` is more intuitive as a name.

**Comment by alexandru** [comment]
Shit ... I modified your message above by mistake, trying to reply to this:

>> It should have a timeout parameter (just like Await.result), after which it should throw a TimeoutException
>
> That's what `unsafeRunTimed` is for.  In my experience, this function really isn't relevant outside of testing.  If you're using it in some sort of mainline production code, there's a problem *somewhere*.

Btw, what function are you talking about?

`Await.result` is very helpful for having a timeout - I've seen an app that suffered from latency, but wasn't crashing, because of that timeout parameter - basically the thread-pool was dried up, with on-complete callbacks having nowhere to execute b/c the threads were blocked waiting for those callbacks to execute, a sort of dead-lock. And I got some reports from other users as well.

**Comment by djspiewak** [comment]
> Well, an IO implementation is more difficult than providing a couple of interfaces meant for middleware and is going to be more unstable.

Why though?

> I was thinking of schrodinger-core to be like the reactive-streams specification in spirit. So schrodinger-core is middleware and other non-Cats projects won't want to depend on it if it's not very light and very stable.

Well, this loops back to the question though: who's problem is this solving?  Scalaz isn't going to depend on it.  Cats won't depend on it (except through the hypothetical cats-effect).  fs2 won't depend on it.  http4s and doobie aren't going to leverage it; they're either going to use `fs2.Task` or a hypothetical `cats.effect.IO`.  So other than potentially Monix, who is helped by a completely independent, dependency-free set of typeclasses?

> Await.result is very helpful for having a timeout - I've seen an app that suffered from latency, but wasn't crashing, because of that timeout parameter - basically the thread-pool was dried up, with on-complete callbacks having nowhere to execute b/c the threads were blocked waiting for those callbacks to execute, a sort of dead-lock. And I got some reports from other users as well.

Right, but if the only `Await.result` in your entire program is at the end of a `main` function… why does it matter?  `unsafeRunTimed` is literally the `Await.result` analogue, but it exists solely for testing, where you expect to have many `unsafeRun`-type calls and need timeouts to be represented as failure.

Regarding JavaScript, a function like this seems like it would solve the problem:

```scala
  def step[R](
      sync: Either[IO[A], A] => IO[R],
      async: ((A => Unit) => Option[IO[A]]) => IO[R]): IO[R] = ???
```

Basically, interpret `IO` up to a sync/async boundary, and then act on that boundary returning either the final result (if it is the end of the computation), or an `IO` which represents the continuation.  The expectation is that you would call this function recursively until termination, but you could do other things with `R` and suspend off the computation somewhere.  You would be able to call `unsafeRunSync` on the results of this computation with the guarantee that it would run to completion on all platforms.

Another way of looking at this is you're providing a way of effectfully interpreting an async computation into a synchronous one.  Maybe that synchronous one doesn't actually produce the final result (maybe it's just setting up a callback chain), or maybe it *does* produce the final result (as is possible with thread blocking on the JVM).  Your `step` functions would have control over this situation.

**Comment by alexandru** [comment]
> Well, this loops back to the question though: who's problem is this solving? Scalaz isn't going to depend on it. ... fs2 won't depend on it.

That's the thing, by keeping it light and stable, I'm hoping that FS2 will depend on it.

As I explained to Michael Pilquist as well, by using these type-classes we can easily describe conversions, e.g:

```scala
def unsafeConvert[F[_], G[_], A](fa: F[A])
  (implicit F: Eventual[F], G: TaskLike[G]): G[A] = {

  G.create[A] { callback =>
    F.unsafeExtractTrySync(fa)(callback) match {
      case ref @ Right(_) => callback(ref)
      case _ => ()
    }
  }
```

And then, in the `Task` implementations themselves, we can have helpers like:

```scala
sealed abstract class Task[A] {
  //...
  def to[G[_]](implicit G: TaskLike[G]): G[A] =
    unsafeConvert[Task, G, A](this)
}

//... instant interoperability:
source.to[fs2.Task]
```

I know this is useful, because I got dozens of requests on the Monix Gitter channel for "*How can I convert a Scalaz Task to Monix's, or vice-versa?*".  

Having both FS2 and Monix convert between their implementations in this way is instant interoperability without much effort or risk.

> Right, but if the only Await.result in your entire program is at the end of a main function… why does it matter?

Because we both know those `unsafePeformSync` calls are not going to be at the end of our programs 😄

You're talking about an ideal. But in many projects you get a mixture of impure and pure code, often written by different people, that has to interoperate. And yes, this means that sometimes `Task` is used as if it's a `Future`, especially because we (the Scala FP community) have advertised it like that.

> Basically, interpret IO up to a sync/async boundary, and then act on that boundary returning either the final result (if it is the end of the computation), or an IO which represents the continuation. The expectation is that you would call this function recursively until termination,

That function is very interesting, but you can't run that function recursively until termination in a *synchronous loop*. Unless I misunderstand of course. But the issue is that you can't necessarily control the evaluation of async processes. Sample:

```scala
Task.async[Int] { callback =>
  // Javascript pseudocode, signal after 1 second
  global.setTimeout(() => callback(Right(1)), 1000)
}
```

You can run your recursive loop all you want, you can't get the result of this without an actual async boundary managed by the JS runtime.

Am I missing something here?

**Comment by alexandru** [comment]
NOTE: if you received an email using `TaskLike` in the snippets above, read that as `Async` (bad copy/paste).

**Comment by alexandru** [comment]
On that `step` function, OK, I think I missed the point there, have to wrap my head around it, it's too lambda for judging it in a single minute :-)

**Comment by djspiewak** [comment]
> Having both FS2 and Monix convert between their implementations in this way is instant interoperability without much effort or risk.

So conversion is the only use-case here then?  How do you address the scenario where a target that you would *like* to be convertable… isn't?  Like `scala.concurrent.Future`.

> Because we both know those unsafePeformSync calls are not going to be at the end of our programs 😄

I'm thinking about other approaches as well.  But I really do put all my `unsafePerformSync` calls exactly once at the end of the program.  If I need to do something in the middle (because of impure code interop), it's *always* an `unsafePerformAsync`.  I don't want an API that encourages people to block threads, even with timeouts.  Really *especially* with timeouts, since then you have resource leakage.

> That function is very interesting, but you can't run that function recursively until termination in a synchronous loop. Unless I misunderstand of course. But the issue is that you can't necessarily control the evaluation of async processes.

The function in question doesn't require you to.  The `async` case produces `None` if the underlying `IO` is fully async, meaning that the result is *instead* going to be passed to the callback given.  The `sync` case produces either the result or the `IO` itself, which may have to be stepped further and may be asynchronous.

So yes, you can actually run it in a synchronous loop.  Note that `R` is not `A`, and might not contain anything to do with `A`.

**Comment by alexandru** [comment]
>>  Having both FS2 and Monix convert between their implementations in this way is instant interoperability without much effort or risk.
>
> So conversion is the only use-case here then? 

I wouldn't say the only use-case, I'd say it's the use-case I'm interested in.

But these type-classes are about describing *side effects*. Note that I made this project to include `Deferrable`, since there were objections to [MonadDefer](https://github.com/typelevel/cats/pull/1552) in Cats.

And I know that @etorreborre wants it. And Doobie [might want it](https://github.com/tpolecat/doobie/blob/series/0.4.x/yax/core/src/main/scala/doobie/util/capture.scala) as well. And @raulraja wants to get rid of their own [Capture](https://github.com/47deg/freestyle/blob/master/freestyle/shared/src/main/scala/freestyle/Capture.scala) as well.

And going from `Deferrable` to `Async` is only natural evolution. Technically they are really similar, except that `Async` is able to capture side-effects triggered by async processes.

> How do you address the scenario where a target that you would like to be convertable… isn't? Like `scala.concurrent.Future`.

I don't see it as a problem, the `Async` restriction should describe what works well enough. `Future` doesn't have the same capabilities, being eager, but given that I made `Future` implement `Eventual[Future]`, we can have:

```scala
Task.from(future)
```

**Comment by rossabaker** [comment]
I got [http4s examples compiling on IO](https://github.com/rossabaker/http4s/tree/io) to see how far I could get on a real project.  I think the instances are the most worth discussing, because they inform the dependency structure:

```scala
  implicit def schrodingersInstances: schrodinger.Deferrable[IO] = ???
  implicit def fs2Instances: fs2.util.Catchable[IO] with fs2.util.Async[IO] = ???
  implicit def catsInstances: cats.Monad[IO] = ???
  implicit def monoidInstance[A: cats.Monoid]: cats.Monoid[IO[A]] = ???
```

* If IO depends on cats-core, it can directly provide the needed cats instances.
* If IO depends on or is part of schrodinger, it could provide `Deferrable[IO]`, which could replace `fs2.util.Suspendable[IO]` if fs2-core also adopted schrodinger.
* If fs2-core does not adopt schrodinger, http4s doesn't get much out of these typeclasses, but still would like this IO.
* If fs2-core does not adopt cats-core, it still needs the fs2-cats interop module.
* `fs2.util.Async[IO]` and `fs2.util.Catchable[IO]` still need to come from somewhere, but that decision tree gets simplified when we answer some of the above.

**Comment by alexandru** [comment]
Thanks @rossabaker,

I just pushed a "bridge" for Scalaz: https://github.com/alexandru/schrodinger/tree/master/scalaz

```scala
// For IO
import schrodinger.scalaz.effects.all._
// For Task
import schrodinger.scalaz.concurrent.all._
// Everything
import schrodinger.scalaz.all._
```

A little conflicted about where these should go, maybe that `shims` project would be better, but the advantage of this is that it doesn't depend on `cats-core`.

**Comment by djspiewak** [comment]
@alexandru Moving discussion back to the old issue, since I think we're basically in a situation where `IO` doesn't mesh with what you're trying to achieve here.

**Comment by alexandru** [comment]
@djspiewak I hope you don't disagree much :-)

I also think these discussions tend to be too long and tend to get off-topic.
IMO you should initiate the `cats-effect` and we should collaborate on it with PRs.
